version: '3.8'

services:
  # MongoDB - Graylog's database
  mongodb:
    image: mongo:6.0
    container_name: graylog-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
    networks:
      - graylog-network
    ports:
      - "27017:27017"

  # OpenSearch - Graylog's search engine
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: graylog-opensearch
    restart: unless-stopped
    environment:
      - cluster.name=graylog
      - node.name=graylog-opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - graylog-network
    ports:
      - "9200:9200"
      - "9600:9600"

  # OpenSearch Dashboards (optional but useful)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: graylog-opensearch-dashboards
    restart: unless-stopped
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - graylog-network
    ports:
      - "5601:5601"
    depends_on:
      - opensearch

  # Graylog Server
  graylog:
    image: graylog/graylog:5.1
    container_name: graylog-server
    restart: unless-stopped
    environment:
      # Change these to secure values in production
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9000/
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_ELASTICSEARCH_HOSTS: http://opensearch:9200
      GRAYLOG_MONGODB_URI: mongodb://admin:password123@mongodb:27017/graylog
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - graylog-network
    ports:
      - "9000:9000"
      - "12201:12201/udp"  # GELF UDP
      - "12201:12201/tcp"  # GELF TCP
      - "1514:1514"        # Syslog TCP
      - "5555:5555/tcp"    # Beats
    depends_on:
      - mongodb
      - opensearch

volumes:
  mongodb_data:
    driver: local
  opensearch_data:
    driver: local
  graylog_data:
    driver: local

networks:
  graylog-network:
    driver: bridge
