apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-pvc
  namespace: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:5.1
        ports:
        - containerPort: 9000
        - containerPort: 12201
        - containerPort: 1514
        - containerPort: 5555
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: graylog-secrets
              key: GRAYLOG_PASSWORD_SECRET
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          valueFrom:
            secretKeyRef:
              name: graylog-secrets
              key: GRAYLOG_ROOT_PASSWORD_SHA2
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          valueFrom:
            configMapKeyRef:
              name: graylog-config
              key: GRAYLOG_HTTP_EXTERNAL_URI
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: graylog-config
              key: GRAYLOG_HTTP_BIND_ADDRESS
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          valueFrom:
            configMapKeyRef:
              name: graylog-config
              key: GRAYLOG_ELASTICSEARCH_HOSTS
        - name: GRAYLOG_MONGODB_URI
          value: "mongodb://$(MONGODB_ROOT_USERNAME):$(MONGODB_ROOT_PASSWORD)@mongodb:27017/$(MONGODB_DATABASE)"
        - name: MONGODB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: graylog-secrets
              key: MONGODB_ROOT_USERNAME
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: graylog-secrets
              key: MONGODB_ROOT_PASSWORD
        - name: MONGODB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: graylog-config
              key: MONGODB_DATABASE
        volumeMounts:
        - name: graylog-storage
          mountPath: /usr/share/graylog/data
      volumes:
      - name: graylog-storage
        persistentVolumeClaim:
          claimName: graylog-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: gelf-udp
    port: 12201
    targetPort: 12201
    protocol: UDP
  - name: gelf-tcp
    port: 12201
    targetPort: 12201
  - name: syslog-tcp
    port: 1514
    targetPort: 1514
  - name: beats
    port: 5555
    targetPort: 5555
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: graylog-nodeport
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30090
  type: NodePort
