apiVersion: v1
kind: Secret
metadata:
  name: graylog-secret
  namespace: graylog
type: Opaque
data:
  # Change these values in production!
  # GRAYLOG_PASSWORD_SECRET: somepasswordpepper
  password-secret: c29tZXBhc3N3b3JkcGVwcGVy
  # GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  root-password-sha2: OGM2OTc2ZTViNTQxMDQxNWJkZTkwOGJkNGRlZTE1ZGZiMTY3YTljODczZmM0YmI4YTgxZjZmMmFiNDQ4YTkxOA==

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graylog-pvc
  namespace: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:5.1
        ports:
        - containerPort: 9000
        - containerPort: 12201
        - containerPort: 1514
        - containerPort: 5555
        env:
        - name: GRAYLOG_PASSWORD_SECRET
          valueFrom:
            secretKeyRef:
              name: graylog-secret
              key: password-secret
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          valueFrom:
            secretKeyRef:
              name: graylog-secret
              key: root-password-sha2
        - name: GRAYLOG_HTTP_EXTERNAL_URI
          value: "http://localhost:9000/"
        - name: GRAYLOG_HTTP_BIND_ADDRESS
          value: "0.0.0.0:9000"
        - name: GRAYLOG_ELASTICSEARCH_HOSTS
          value: "http://opensearch:9200"
        - name: GRAYLOG_MONGODB_URI
          value: "mongodb://admin:password123@mongodb:27017/graylog"
        volumeMounts:
        - name: graylog-storage
          mountPath: /usr/share/graylog/data
      volumes:
      - name: graylog-storage
        persistentVolumeClaim:
          claimName: graylog-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  - name: gelf-udp
    port: 12201
    targetPort: 12201
    protocol: UDP
  - name: gelf-tcp
    port: 12201
    targetPort: 12201
  - name: syslog-tcp
    port: 1514
    targetPort: 1514
  - name: beats
    port: 5555
    targetPort: 5555
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: graylog-nodeport
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    nodePort: 30090
  type: NodePort
