apiVersion: v1
kind: Secret
metadata:
  name: graylog-secrets
  namespace: graylog
type: Opaque
stringData:
  # Graylog Secrets - CHANGE THESE IN PRODUCTION!
  GRAYLOG_PASSWORD_SECRET: "your-secure-password-secret-here"
  GRAYLOG_ROOT_PASSWORD: "admin"
  GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
  
  # MongoDB Secrets - CHANGE THESE IN PRODUCTION!
  MONGODB_ROOT_USERNAME: "admin"
  MONGODB_ROOT_PASSWORD: "your-secure-mongodb-password-here"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-config
  namespace: graylog
type: Opaque
stringData:
  # Storage Sizes
  MONGODB_STORAGE_SIZE: "10Gi"
  OPENSEARCH_STORAGE_SIZE: "20Gi"
  GRAYLOG_STORAGE_SIZE: "10Gi"
  
  # Resource Limits
  GRAYLOG_MEMORY_LIMIT: "2Gi"
  GRAYLOG_MEMORY_REQUEST: "1Gi"
  OPENSEARCH_MEMORY_LIMIT: "2Gi"
  OPENSEARCH_MEMORY_REQUEST: "1Gi"
  MONGODB_MEMORY_LIMIT: "1Gi"
  MONGODB_MEMORY_REQUEST: "512Mi"
